######################################################################
# Automatically generated by qmake (2.01a) dom jun 6 17:57:57 2010
######################################################################

TEMPLATE = lib
QT += svg
CONFIG += plugin static
TARGET = svgz
DEPENDPATH += . zlib
INCLUDEPATH += . zlib

# Input
HEADERS += qtsvgz_engine.h qtsvgz_plugin.h zlib/zconf.h zlib/zlib.h
SOURCES += qtsvgz_engine.cpp qtsvgz_plugin.cpp
